add CartPage, CheckOutPage,specification createNewOrderCart
vaspashkevich/Automation pull request #6
Opened 2023-09-04 15:03 UTC by MMalyshava

New specification createNewOrderCart, CartPage and CheckOutPage creation.

2023-09-04 15:35 UTC, panvutka requested changes

2023-09-04 15:35 UTC, panvutka commented on pageObject/CheckOutPage.js
> +    async pressStep2Btn() {
Please locate all selectors first and then all methods

2023-09-04 15:35 UTC, panvutka commented on pageObject/CheckOutPage.js
> +    async fillCardholderName(name) {
Not critical. But to my mind enterCardHolderName sounds better here. Because when we use "fill", we usually say what to fill (e.g. fill in this field). But if you are disagree, it is also ok and can be discussed with Valisiy. If you agree, please change all fill to enter

2023-09-04 15:35 UTC, panvutka commented on pageObject/CheckOutPage.js
> +    InvoiceAddressCity = {
I don't see any methods for next 3 locators. Is it correct?

2023-09-04 15:35 UTC, panvutka commented on pageObject/CheckOutPage.js
> +    async Step5Btn() {
Please use verb for methods here and in all other places, like click or enter. E.g. clickStep5Bth

2023-09-04 15:35 UTC, panvutka commented on pageObject/CheckOutPage.js
> +    PaymentTypeCreditCardBtn = {
First letter for all methods and variables should be small, not capital. Please chnage it here and in all other places

2023-09-04 15:35 UTC, panvutka commented on spec/createNewOrderCart.js
> +    // await browser.pause(5000)
Please remove all unnecessary comments

2023-09-04 15:35 UTC, panvutka commented on spec/createNewOrderCart.js
> +  it('Step 8: Fill in CardholdersName', async function () {
I suggest to use bigger and more meaningfull steps. Like completed business action. E.g. one step with name "Fill in payment info" instead of steps 8 - 11

2023-09-04 15:35 UTC, panvutka commented on spec/createNewOrderCart.js
> +    const valueToEnter = "Marya Malyshava";
Please move out data for test to the data file. Or at least to the beginning of the test

2023-09-05 09:40 UTC, MMalyshava commented on pageObject/CheckOutPage.js
> +    async pressStep2Btn() {
Done

2023-09-05 09:51 UTC, MMalyshava commented on pageObject/CheckOutPage.js
> +    async fillCardholderName(name) {
I agree with you. I corrected all fill to enter.

2023-09-05 09:53 UTC, MMalyshava commented on pageObject/CheckOutPage.js
> +    InvoiceAddressCity = {
Yes, lets discuss it at the meeting.

2023-09-05 10:07 UTC, MMalyshava commented on pageObject/CheckOutPage.js
> +    async Step5Btn() {
Done

2023-09-05 10:10 UTC, MMalyshava commented on pageObject/CheckOutPage.js
> +    PaymentTypeCreditCardBtn = {
Done

2023-09-05 10:25 UTC, MMalyshava commented on spec/createNewOrderCart.js
> +    // await browser.pause(5000)
Done

2023-09-05 11:19 UTC, MMalyshava commented on spec/createNewOrderCart.js
> +  it('Step 8: Fill in CardholdersName', async function () {
Done

2023-09-05 11:21 UTC, MMalyshava commented on spec/createNewOrderCart.js
> +    const valueToEnter = "Marya Malyshava";
If I correctly understand this comment relates the previous one?

2023-09-05 14:26 UTC, panvutka requested changes

2023-09-05 14:26 UTC, panvutka commented on data/orderCart.json
> +
Extra line

2023-09-05 14:26 UTC, panvutka commented on pageObject/CheckOutPage.js
> +    step2Button = {
Please use Button or Btn in all names. using both options are not ok

2023-09-05 14:26 UTC, panvutka commented on pageObject/CartPage.js
> +    async pressProceedBtn() {
Need empty line before new method

2023-09-05 14:26 UTC, panvutka commented on pageObject/CheckOutPage.js
> +
Extra line

2023-09-05 14:26 UTC, panvutka commented on spec/createNewOrderCart.js
> +  it('Step 13: Fill in InvoiceAddress', async function () {
Please combine into one step as Payment Info

2023-09-05 15:38 UTC, panvutka approved these changes

2023-09-05 15:43 UTC, merged